#
#
#
#
#
#
#
#
#    datasource:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/accounts
#      username:
#      password:
#      jpa:
#        hibernate.ddl-auto: update
#        generate-ddl: true
#        show-sql: true