version: '3.8'
services:
  postegres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data



#version: '3.1'
#
#services:
#
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 5432:5432



